### ISSUE TITLE
please document origin of licensing terms

### ISSUE THREAD

**Issue by jonassmedegaard** [googlefonts/atkinson-hyperlegible#1]
Hi Dave,

This project says that the font is licensed under a SIL 1.1 license, but the upstream website seemingly released the font only under (very slmilar but) terms not identified as the SIL OFL.

Please clarify how it was resolved to be legally acceptable to use this redistributed font under the SIL OFL.

**Comment by davelab6** [comment]
I worked with the Braille Institute to change the license.

**Comment by Aspie96** [comment]
@davelab6 on their website this license is still used.

Can the font be assumed to be dual-licensed under their own license or (at the user's option) the OFL license?

EDIT: Nevermind, I just noticed: https://github.com/google/fonts/issues/3159#issuecomment-892707354
It'd be helpful if they had mentioned the previous license, but I think it's fair to assume it's 1.1.
