### ISSUE TITLE
How can we be notified when this font is available in Google Fonts?

### ISSUE THREAD

**Issue by mathiasfoster** [googlefonts/atkinson-hyperlegible#5]
I have been watching the progress of this font over time – looking forward to its' inclusion in Google Fonts, so we can use it in Google Docs.

How can we be notified when this becomes available / is there any easy way to check the status?

**Comment by cmbartschat** [comment]
If you haven't seen yet, it's showing up in Drive for me now, and can be seen here:

https://fonts.google.com/specimen/Atkinson+Hyperlegible

**Comment by mathiasfoster** [comment]
Excellent! Working for me now also.
